#本文件为本脚本项目使用的全功能配置文件。
#不同语言项目使用这个统一的全功能配置文件。
#不同语言项目可能存在不同的参数默认值，请在对应的语言子目录下的_ci-cd-config.yaml文件中配置。
globalParams:
  #Web前端项目需要手动配置serviceName参数的值。
  #无法像后端服务可通过参数映射文件进行配置
  serviceName: vue-demo
  #服务中文名称
  name: vue样例程序
  #Web前端项目需要手动配置businessVersion参数的值。
  #无法像后端服务可通过参数映射文件进行配置
  businessVersion: 1.0.0
  #设定主端口
  mainPort: 3004

  #应用设置的路由前缀参数。
  #todo: 应等于vue.config.js配置文件中的publicPath(必须配置)参数的值。
  gatewayPath: /vue
  #路由重写Uri参数, 设置为空串表示不启用路由重写功能。
  #默认设置为仅包含一个空格的字符串，表示删除路由路径中前导的gatewayPath参数串。
  #todo: 特别说明，vue项目不要启用路由重写，如果启用则会导致部分静态资源访问失败
  rewriteUri: ""
  #使用istio时Gateway资源绑定的Host名称，*表示任意Host。
  gatewayHost: www.wydevops.com

  #目标K8S集群的ApiServer服务器的地址信息（必须配置）
  #格式：{服务器IP地址}|{SSH端口号}|{SSH连接账号}|{SSH连接密码}
  targetApiServer: 172.27.206.206|22|wuyi|Wpl118124
  #部署的命名空间
  targetNamespace: default
  #K8s集群内部拉取镜像的仓库信息：
  #格式：{仓库类型(nexus或harbor)},{仓库实例名称(nexus)或项目名称(harbor)},{仓库访问地址({IP}:{端口})},{登录账号},{登录密码}
  targetDockerRepo: nexus,wydevops,192.168.31.218:8001,admin,Wpl118124,8081

  #参数不为空时即表示需要挂载PVC，参数值即为PVC资源名称。
  #挂载路径默认为vue-demo-workdir
  persistentVolumeClaimName: csi-s3-pvc
deploy:
  - name: ${chartName}
    params: 
