app:
  env: local
  #wydevops会读取port参数。
  port: 8888
  appName: gin-app123
  appUrl: http://localhost
  #wydevops会读取app.gateway.url-prefix参数。
  gateway:
    domain: localhost
    route-prefix: /gin
  #wydevops会读取version参数。
  version: 1.0.0
  mysql:
    host: mysql:3306
    username: root
    password: root123456
