app:
  env: local
  #wydevops会读取port参数。
  port: 8888
  appName: gin-app123
  appUrl: http://localhost
  #wydevops会读取apiUrlPrefix参数。
  apiUrlPrefix: /gin
  #wydevops会读取version参数。
  version: 1.0.0
  mysql:
    host: {{ .Values.params.mysql.host | default "mysql:3306" }}
    username: {{ .Values.params.mysql.username | default "root" }}
    password: {{ .Values.params.mysql.password | default "root123456" }}
