server:
  port: 8062

#网关配置
gateway:
  #网关域名
  domain: www.wydevops.com
  #网关路由前缀
  url-prefix: /java-sample/v1/api

mysql-params:
  host: {{ .Values.params.mysql.host | default "192.168.31.218" }}
  port: {{ .Values.params.mysql.port | default "3306" }}
  username: {{ .Values.params.mysql.username | default "root" }}
  password: {{ .Values.params.mysql.password | default "123456" }}

myName: {{ .Values.params.myName | default "wydevops" }}

#以下是具体使用上面定义的变量。
#spring:
#  datasource:
#    url: jdbc:mysql://${mysql-params.host}:${mysql-params.port}/test2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: ${mysql-params.username}
#    password: ${mysql-params.password}
